# Generated by Django 4.2.8 on 2024-01-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='img_work',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
