# Generated by Django 4.2.8 on 2023-12-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_work', models.CharField(max_length=50)),
                ('text_work', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=255, verbose_name='URL')),
            ],
        ),
    ]
