# Generated by Django 4.2.8 on 2023-12-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_comments_username_comments_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default='2023-12-14 22:59:52', verbose_name='дата публикации'),
        ),
    ]
