# Generated by Django 4.2.8 on 2024-01-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_work_img_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='img_work',
            field=models.FileField(upload_to='uplouds_model'),
        ),
    ]
