# Generated by Django 4.2.8 on 2024-01-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_work_img_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='img_work',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uplouds_model/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
